######################################################################
# Automatically generated by qmake (2.00a) óÂÔ æÅ× 25 11:18:39 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dsanim.h mainwindow.h translate.h
SOURCES += dsanim.cpp main.cpp mainwindow.cpp
